_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.12.5
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 2
                - 3
                - 14
                - 55
            "4": 3.12.5
            "5": 0.20.1
            "12": 0.20.1
            "13": darwin-x86_64
        visualize:
            confusion_matrix:
                panel_config:
                    fieldSettings:
                        Actual: Actual
                        Predicted: Predicted
                        nPredictions: nPredictions
                    panelDefId: wandb/confusion_matrix/v1
                    stringSettings:
                        title: Confusion Matrix Curve
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: confusion_matrix_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
batch_size:
    value: 32
depth:
    value: 8
dropout:
    value: 0.08580316212045193
embed_dim:
    value: 128
epochs:
    value: 1
learning_rate:
    value: 0.0022362004039124103
mlp_ratio:
    value: 8
num_heads:
    value: 4
patch_size:
    value: 7
use_cls_token:
    value: true
weight_decay:
    value: 0.013847924571429311
