_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.12.5
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 2
                - 14
                - 55
            "4": 3.12.5
            "5": 0.20.1
            "12": 0.20.1
            "13": darwin-x86_64
batch_size:
    value: 64
depth:
    value: 8
dropout:
    value: 0.12641107472942034
embed_dim:
    value: 128
epochs:
    value: 5
learning_rate:
    value: 0.0012092228909578123
mlp_ratio:
    value: 2
num_heads:
    value: 4
patch_size:
    value: 7
use_cls_token:
    value: true
weight_decay:
    value: 0.004244068466959918
