wandb_version: 1

batch_size:
  value: 64
depth:
  value: 4
dropout:
  value: 0.21722898314785755
embed_dim:
  value: 64
epochs:
  value: 5
learning_rate:
  value: 0.0001054030692215179
mlp_ratio:
  value: 8
num_heads:
  value: 4
patch_size:
  value: 7
use_cls_token:
  value: true
weight_decay:
  value: 0.007463200445359919
