wandb_version: 1

batch_size:
  value: 16
depth:
  value: 6
dropout:
  value: 0.15264406328267507
embed_dim:
  value: 64
epochs:
  value: 5
learning_rate:
  value: 0.0013194508914191844
mlp_ratio:
  value: 8
num_heads:
  value: 4
patch_size:
  value: 7
use_cls_token:
  value: true
weight_decay:
  value: 0.04921997337231053
