wandb_version: 1

batch_size:
  value: 32
depth:
  value: 6
dropout:
  value: 0.2942514466281283
embed_dim:
  value: 64
epochs:
  value: 5
learning_rate:
  value: 0.00013433657508506042
mlp_ratio:
  value: 2
num_heads:
  value: 16
patch_size:
  value: 7
use_cls_token:
  value: true
weight_decay:
  value: 0.004378892608734709
