wandb_version: 1

batch_size:
  value: 32
depth:
  value: 4
dropout:
  value: 0.16028057728515951
embed_dim:
  value: 64
epochs:
  value: 5
learning_rate:
  value: 0.001394250893698965
mlp_ratio:
  value: 2
num_heads:
  value: 16
patch_size:
  value: 7
use_cls_token:
  value: true
weight_decay:
  value: 0.001876978002467958
