wandb_version: 1

batch_size:
  value: 32
depth:
  value: 6
dropout:
  value: 0.23453623267199877
embed_dim:
  value: 128
epochs:
  value: 5
learning_rate:
  value: 0.00810096259900732
mlp_ratio:
  value: 8
num_heads:
  value: 16
patch_size:
  value: 7
use_cls_token:
  value: true
weight_decay:
  value: 0.00656270877752013
