wandb_version: 1

batch_size:
  value: 16
depth:
  value: 4
dropout:
  value: 0.20663365210537837
embed_dim:
  value: 128
epochs:
  value: 5
learning_rate:
  value: 0.0013058230593062214
mlp_ratio:
  value: 2
num_heads:
  value: 4
patch_size:
  value: 7
use_cls_token:
  value: true
weight_decay:
  value: 0.021049661202381737
