wandb_version: 1

batch_size:
  value: 32
depth:
  value: 6
dropout:
  value: 0.19982335466407505
embed_dim:
  value: 64
epochs:
  value: 5
learning_rate:
  value: 0.0001578664946110011
mlp_ratio:
  value: 8
num_heads:
  value: 8
patch_size:
  value: 7
use_cls_token:
  value: true
weight_decay:
  value: 0.006169244191212478
