wandb_version: 1

batch_size:
  value: 32
depth:
  value: 4
dropout:
  value: 0.2568327660352471
embed_dim:
  value: 32
epochs:
  value: 5
learning_rate:
  value: 0.009362853118758544
mlp_ratio:
  value: 4
num_heads:
  value: 16
patch_size:
  value: 7
use_cls_token:
  value: true
weight_decay:
  value: 0.00898487757633804
