wandb_version: 1

batch_size:
  value: 16
depth:
  value: 8
dropout:
  value: 0.17419162321736675
embed_dim:
  value: 128
epochs:
  value: 1
learning_rate:
  value: 0.007207016166858184
mlp_ratio:
  value: 4
num_heads:
  value: 4
patch_size:
  value: 7
use_cls_token:
  value: true
weight_decay:
  value: 0.001479956011886157
