wandb_version: 1

batch_size:
  value: 64
depth:
  value: 4
dropout:
  value: 0.22522429631851976
embed_dim:
  value: 64
epochs:
  value: 1
learning_rate:
  value: 0.007873482593335021
mlp_ratio:
  value: 8
num_heads:
  value: 16
patch_size:
  value: 7
use_cls_token:
  value: true
weight_decay:
  value: 0.07147101958281815
