wandb_version: 1

batch_size:
  value: 64
depth:
  value: 6
dropout:
  value: 0.1438007432561625
embed_dim:
  value: 64
epochs:
  value: 1
learning_rate:
  value: 0.00032585055282609315
mlp_ratio:
  value: 4
num_heads:
  value: 4
patch_size:
  value: 7
use_cls_token:
  value: true
weight_decay:
  value: 0.001260721262683764
