program: encoder_only_models.py
method: bayes
metric:
  name: test_accuracy
  goal: maximize
parameters:
  learning_rate:
    distribution: log_uniform_values
    min: 1e-5
    max: 1e-2
  batch_size_train:
    values: [64, 128, 256]
  d_model:
    values: [128, 256, 384]
  n_heads:
    values: [4, 8, 12]
  depth:
    values: [4, 6, 8]
  patch_size:
    values: [4, 7]
  dropout:
    distribution: uniform
    min: 0.1
    max: 0.3
  num_epochs:
    value: 10
early_terminate:
  type: hyperband
  min_iter: 3
